# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hangman-backend-docker/mi-app:$SHORT_SHA',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hangman-backend-docker/mi-app:latest',
        '.'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/hangman-backend-docker/mi-app:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/hangman-backend-docker/mi-app:latest' 
