# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-southwest1-docker.pkg.dev/$PROJECT_ID/hangman-backend-docker/mi-app:$SHORT_SHA',
        '.'
      ]

images:
  - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/hangman-backend-docker/mi-app:$SHORT_SHA'
